import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const templates = [
  {
    id: "tmpl_arrendamiento",
    name: "Contrato de Arrendamiento de Inmueble",
    description: "Contrato de arrendamiento residencial o comercial conforme al Código Civil de la Ciudad de México (CCCDMX)",
    category: "LEASE" as const,
    areaOfLaw: "CIVIL" as const,
    variables: {
      fields: [
        { key: "arrendador_nombre", label: "Nombre completo del arrendador", type: "text", required: true },
        { key: "arrendador_genero", label: "Género del arrendador (M/F)", type: "text", required: true },
        { key: "arrendador_rfc", label: "RFC del arrendador", type: "text", required: false },
        { key: "arrendador_domicilio", label: "Domicilio del arrendador (para notificaciones)", type: "text", required: true },
        { key: "arrendatario_nombre", label: "Nombre completo del arrendatario", type: "text", required: true },
        { key: "arrendatario_genero", label: "Género del arrendatario (M/F)", type: "text", required: true },
        { key: "arrendatario_rfc", label: "RFC del arrendatario", type: "text", required: false },
        { key: "inmueble_direccion", label: "Dirección completa del inmueble", type: "text", required: true },
        { key: "renta_mensual", label: "Renta mensual (MXN)", type: "number", required: true },
        { key: "deposito_garantia", label: "Depósito de garantía (MXN)", type: "number", required: true },
        { key: "fecha_inicio", label: "Fecha de inicio del contrato", type: "date", required: true },
        { key: "duracion_meses", label: "Duración en meses", type: "number", required: true },
        { key: "uso_inmueble", label: "Uso del inmueble (habitacional/comercial)", type: "text", required: true },
        { key: "servicios_incluidos", label: "Servicios incluidos en la renta (agua, luz, gas, etc.)", type: "text", required: true },
        { key: "ciudad", label: "Ciudad", type: "text", required: true },
      ],
    },
    content: JSON.stringify({
      type: "doc",
      content: [
        { type: "heading", attrs: { level: 1 }, content: [{ type: "text", text: "CONTRATO DE ARRENDAMIENTO DE INMUEBLE" }] },
        { type: "paragraph", content: [{ type: "text", text: "En {{ciudad}}, a {{fecha_inicio}}, ante los testigos que al final suscriben, COMPARECEN:" }] },
        { type: "heading", attrs: { level: 2 }, content: [{ type: "text", text: "COMPARECEN" }] },
        { type: "paragraph", content: [{ type: "text", text: "Por una parte: {{arrendador_nombre}}, en adelante denominado/a \"EL ARRENDADOR\" (género: {{arrendador_genero}})." }] },
        { type: "paragraph", content: [{ type: "text", text: "Por la otra parte: {{arrendatario_nombre}}, en adelante denominado/a \"EL ARRENDATARIO\" (género: {{arrendatario_genero}})." }] },
        { type: "heading", attrs: { level: 2 }, content: [{ type: "text", text: "DECLARAN" }] },
        { type: "paragraph", content: [{ type: "text", text: "I. EL ARRENDADOR declara ser legítimo propietario/a del inmueble ubicado en {{inmueble_direccion}}, y tener plena capacidad jurídica para celebrar el presente contrato." }] },
        { type: "paragraph", content: [{ type: "text", text: "II. EL ARRENDATARIO declara tener interés en arrendar el inmueble antes descrito para destinarlo exclusivamente a uso {{uso_inmueble}}." }] },
        { type: "heading", attrs: { level: 2 }, content: [{ type: "text", text: "CLÁUSULAS" }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "PRIMERA. OBJETO" }] },
        { type: "paragraph", content: [{ type: "text", text: "EL ARRENDADOR da en arrendamiento a EL ARRENDATARIO el inmueble ubicado en {{inmueble_direccion}}, para uso {{uso_inmueble}}, en términos del artículo 2398 del Código Civil de la Ciudad de México (CCCDMX)." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "SEGUNDA. VIGENCIA" }] },
        { type: "paragraph", content: [{ type: "text", text: "El presente contrato tendrá vigencia de {{duracion_meses}} meses, contados a partir del {{fecha_inicio}}, prorrogable de común acuerdo por escrito." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "TERCERA. RENTA" }] },
        { type: "paragraph", content: [{ type: "text", text: "EL ARRENDATARIO se obliga a pagar a EL ARRENDADOR la cantidad de ${{renta_mensual}}.00 M.N. como renta mensual, los primeros cinco días naturales de cada mes, en el domicilio convencional de EL ARRENDADOR señalado en la Cláusula Décima, o mediante transferencia electrónica a la cuenta que EL ARRENDADOR indique por escrito." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "CUARTA. DEPÓSITO EN GARANTÍA" }] },
        { type: "paragraph", content: [{ type: "text", text: "EL ARRENDATARIO entrega en este acto la cantidad de ${{deposito_garantia}}.00 M.N. como depósito en garantía, misma que será devuelta al término del contrato previa verificación del estado del inmueble y del inventario, sin intereses, conforme al artículo 2431 del CCCDMX." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "QUINTA. SERVICIOS" }] },
        { type: "paragraph", content: [{ type: "text", text: "Los servicios incluidos en la renta son: {{servicios_incluidos}}. Los servicios no incluidos serán contratados y pagados directamente por EL ARRENDATARIO, quien asumirá la responsabilidad de mantenerlos al corriente durante toda la vigencia del contrato." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "SEXTA. INVENTARIO" }] },
        { type: "paragraph", content: [{ type: "text", text: "Las partes reconocen que el inmueble se entrega con el mobiliario, enseres y accesorios descritos en el Inventario que se adjunta al presente contrato como Anexo \"A\", el cual forma parte integrante del mismo. EL ARRENDATARIO se obliga a devolver el inmueble con todos los bienes del inventario en las mismas condiciones en que los recibió, salvo el desgaste natural por el uso ordinario." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "SÉPTIMA. OBLIGACIONES DEL ARRENDATARIO" }] },
        { type: "paragraph", content: [{ type: "text", text: "EL ARRENDATARIO se obliga a: a) Pagar puntualmente la renta en los términos pactados; b) Conservar el inmueble en buen estado; c) No subarrendar ni ceder los derechos del presente contrato sin autorización escrita de EL ARRENDADOR; d) Usar el inmueble exclusivamente para el fin pactado; e) Permitir inspecciones al inmueble con previo aviso de 48 horas; f) No realizar obras o modificaciones sin autorización escrita previa." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "OCTAVA. CLÁUSULA PENAL" }] },
        { type: "paragraph", content: [{ type: "text", text: "En caso de incumplimiento de cualquiera de las obligaciones del presente contrato, la parte infractora pagará a la parte afectada una pena convencional equivalente al 20% del monto total de las rentas pactadas, sin perjuicio del cumplimiento forzoso o rescisión, en términos del artículo 1840 del CCCDMX." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "NOVENA. RESOLUCIÓN DE CONTROVERSIAS" }] },
        { type: "paragraph", content: [{ type: "text", text: "Para la interpretación y cumplimiento del presente contrato, las partes se someten expresamente a la jurisdicción de los Tribunales competentes de {{ciudad}}, renunciando al fuero que pudiere corresponderles por razón de su domicilio presente o futuro." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "DÉCIMA. DOMICILIOS CONVENCIONALES" }] },
        { type: "paragraph", content: [{ type: "text", text: "Para efectos del presente contrato y para cualquier notificación judicial o extrajudicial, las partes señalan como domicilios convencionales los siguientes:\n\nEL ARRENDADOR: {{arrendador_domicilio}}.\n\nEL ARRENDATARIO: {{inmueble_direccion}} (el inmueble objeto del presente contrato)." }] },
        { type: "paragraph", content: [{ type: "text", text: "Leído que fue el presente contrato por las partes, enteradas de su contenido y alcance legal, y estando de acuerdo con todas y cada una de sus cláusulas, lo firman en {{ciudad}}, el {{fecha_inicio}}." }] },
        { type: "paragraph", content: [{ type: "text", text: "_________________________\nEL ARRENDADOR\n{{arrendador_nombre}}\nRFC: {{arrendador_rfc}}" }] },
        { type: "paragraph", content: [{ type: "text", text: "_________________________\nEL ARRENDATARIO\n{{arrendatario_nombre}}\nRFC: {{arrendatario_rfc}}" }] },
        { type: "heading", attrs: { level: 2 }, content: [{ type: "text", text: "TESTIGOS" }] },
        { type: "paragraph", content: [{ type: "text", text: "_________________________\nPRIMER TESTIGO\nNombre: ___________________________\nDomicilio: ___________________________\nFirma: ___________________________" }] },
        { type: "paragraph", content: [{ type: "text", text: "_________________________\nSEGUNDO TESTIGO\nNombre: ___________________________\nDomicilio: ___________________________\nFirma: ___________________________" }] },
      ],
    }),
  },
  {
    id: "tmpl_servicios_profesionales",
    name: "Contrato de Prestación de Servicios Profesionales",
    description: "Contrato para servicios legales y profesionales independientes conforme al CCF",
    category: "CONTRACT" as const,
    areaOfLaw: "CIVIL" as const,
    variables: {
      fields: [
        { key: "prestador_nombre", label: "Nombre del prestador de servicios", type: "text", required: true },
        { key: "prestador_cedula", label: "Cédula profesional", type: "text", required: false },
        { key: "cliente_nombre", label: "Nombre del cliente", type: "text", required: true },
        { key: "cliente_rfc", label: "RFC del cliente", type: "text", required: false },
        { key: "descripcion_servicios", label: "Descripción de los servicios", type: "text", required: true },
        { key: "honorarios", label: "Honorarios (MXN)", type: "number", required: true },
        { key: "forma_pago", label: "Forma de pago", type: "text", required: true },
        { key: "plazo_dias", label: "Plazo de entrega (días)", type: "number", required: true },
        { key: "ciudad", label: "Ciudad", type: "text", required: true },
      ],
    },
    content: JSON.stringify({
      type: "doc",
      content: [
        { type: "heading", attrs: { level: 1 }, content: [{ type: "text", text: "CONTRATO DE PRESTACIÓN DE SERVICIOS PROFESIONALES" }] },
        { type: "paragraph", content: [{ type: "text", text: "En la Ciudad de {{ciudad}}, a _____ de __________ de _____, COMPARECEN:" }] },
        { type: "heading", attrs: { level: 2 }, content: [{ type: "text", text: "COMPARECEN" }] },
        { type: "paragraph", content: [{ type: "text", text: "EL PRESTADOR: {{prestador_nombre}}, Cédula Profesional {{prestador_cedula}}, en adelante \"EL PRESTADOR\"." }] },
        { type: "paragraph", content: [{ type: "text", text: "EL CLIENTE: {{cliente_nombre}}, RFC {{cliente_rfc}}, en adelante \"EL CLIENTE\"." }] },
        { type: "heading", attrs: { level: 2 }, content: [{ type: "text", text: "CLÁUSULAS" }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "PRIMERA. OBJETO" }] },
        { type: "paragraph", content: [{ type: "text", text: "EL PRESTADOR se obliga a proporcionar a EL CLIENTE los siguientes servicios profesionales: {{descripcion_servicios}}, en términos del artículo 2606 del CCF." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "SEGUNDA. HONORARIOS" }] },
        { type: "paragraph", content: [{ type: "text", text: "EL CLIENTE pagará a EL PRESTADOR la cantidad de ${{honorarios}}.00 M.N. más IVA correspondiente. Forma de pago: {{forma_pago}}." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "TERCERA. PLAZO" }] },
        { type: "paragraph", content: [{ type: "text", text: "Los servicios serán entregados en un plazo de {{plazo_dias}} días hábiles a partir de la firma del presente contrato." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "CUARTA. CONFIDENCIALIDAD" }] },
        { type: "paragraph", content: [{ type: "text", text: "EL PRESTADOR se obliga a guardar absoluta confidencialidad respecto de la información que EL CLIENTE le proporcione, obligación que subsistirá aún después de la terminación del presente contrato." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "QUINTA. CLÁUSULA PENAL" }] },
        { type: "paragraph", content: [{ type: "text", text: "El incumplimiento de cualquiera de las obligaciones del presente contrato generará una pena convencional equivalente al 15% del monto total de los honorarios pactados." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "SEXTA. JURISDICCIÓN" }] },
        { type: "paragraph", content: [{ type: "text", text: "Para la resolución de cualquier controversia derivada del presente contrato, las partes se someten a la jurisdicción de los Tribunales de {{ciudad}}, renunciando al fuero de su domicilio." }] },
        { type: "paragraph", content: [{ type: "text", text: "Firman en {{ciudad}} en la fecha indicada al inicio.\n\n_________________________\nEL PRESTADOR\n{{prestador_nombre}}\n\n_________________________\nEL CLIENTE\n{{cliente_nombre}}" }] },
      ],
    }),
  },
  {
    id: "tmpl_compraventa_mueble",
    name: "Contrato de Compraventa de Bien Mueble",
    description: "Contrato de compraventa de bienes muebles conforme al artículo 2248 del CCF",
    category: "CONTRACT" as const,
    areaOfLaw: "CIVIL" as const,
    variables: {
      fields: [
        { key: "vendedor_nombre", label: "Nombre del vendedor", type: "text", required: true },
        { key: "comprador_nombre", label: "Nombre del comprador", type: "text", required: true },
        { key: "descripcion_bien", label: "Descripción del bien mueble", type: "text", required: true },
        { key: "precio", label: "Precio de venta (MXN)", type: "number", required: true },
        { key: "forma_pago", label: "Forma de pago", type: "text", required: true },
        { key: "lugar_entrega", label: "Lugar de entrega", type: "text", required: true },
        { key: "ciudad", label: "Ciudad", type: "text", required: true },
      ],
    },
    content: JSON.stringify({
      type: "doc",
      content: [
        { type: "heading", attrs: { level: 1 }, content: [{ type: "text", text: "CONTRATO DE COMPRAVENTA DE BIEN MUEBLE" }] },
        { type: "paragraph", content: [{ type: "text", text: "En {{ciudad}}, a _____ de __________ de _____, COMPARECEN:" }] },
        { type: "paragraph", content: [{ type: "text", text: "EL VENDEDOR: {{vendedor_nombre}}.\nEL COMPRADOR: {{comprador_nombre}}." }] },
        { type: "heading", attrs: { level: 2 }, content: [{ type: "text", text: "CLÁUSULAS" }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "PRIMERA. OBJETO" }] },
        { type: "paragraph", content: [{ type: "text", text: "EL VENDEDOR transmite la propiedad de: {{descripcion_bien}}, a EL COMPRADOR, en términos del artículo 2248 del Código Civil Federal." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "SEGUNDA. PRECIO" }] },
        { type: "paragraph", content: [{ type: "text", text: "El precio pactado es de ${{precio}}.00 M.N. Forma de pago: {{forma_pago}}." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "TERCERA. ENTREGA" }] },
        { type: "paragraph", content: [{ type: "text", text: "EL VENDEDOR entregará el bien en {{lugar_entrega}}, libre de gravámenes y en perfecto estado de funcionamiento." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "CUARTA. SANEAMIENTO" }] },
        { type: "paragraph", content: [{ type: "text", text: "EL VENDEDOR responderá por evicción y vicios ocultos conforme a los artículos 2119 y 2142 del CCF." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "QUINTA. JURISDICCIÓN" }] },
        { type: "paragraph", content: [{ type: "text", text: "Las partes se someten a los Tribunales de {{ciudad}} para la resolución de controversias." }] },
        { type: "paragraph", content: [{ type: "text", text: "Firman en {{ciudad}}.\n\n_________________________\nEL VENDEDOR: {{vendedor_nombre}}\n\n_________________________\nEL COMPRADOR: {{comprador_nombre}}" }] },
      ],
    }),
  },
  {
    id: "tmpl_nda",
    name: "Convenio de Confidencialidad (NDA)",
    description: "Acuerdo de no divulgación de información confidencial para relaciones comerciales",
    category: "NDA" as const,
    areaOfLaw: "MERCANTIL" as const,
    variables: {
      fields: [
        { key: "divulgante_nombre", label: "Nombre de la parte divulgante", type: "text", required: true },
        { key: "receptor_nombre", label: "Nombre de la parte receptora", type: "text", required: true },
        { key: "proposito", label: "Propósito de la divulgación", type: "text", required: true },
        { key: "vigencia_meses", label: "Vigencia en meses", type: "number", required: true },
        { key: "ciudad", label: "Ciudad", type: "text", required: true },
      ],
    },
    content: JSON.stringify({
      type: "doc",
      content: [
        { type: "heading", attrs: { level: 1 }, content: [{ type: "text", text: "CONVENIO DE CONFIDENCIALIDAD Y NO DIVULGACIÓN" }] },
        { type: "paragraph", content: [{ type: "text", text: "En {{ciudad}}, a _____ de __________ de _____, celebran el presente Convenio de Confidencialidad:" }] },
        { type: "paragraph", content: [{ type: "text", text: "LA PARTE DIVULGANTE: {{divulgante_nombre}}\nLA PARTE RECEPTORA: {{receptor_nombre}}" }] },
        { type: "heading", attrs: { level: 2 }, content: [{ type: "text", text: "CLÁUSULAS" }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "PRIMERA. OBJETO Y PROPÓSITO" }] },
        { type: "paragraph", content: [{ type: "text", text: "Las partes intercambiarán información confidencial con el único propósito de: {{proposito}}." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "SEGUNDA. INFORMACIÓN CONFIDENCIAL" }] },
        { type: "paragraph", content: [{ type: "text", text: "Se considera Información Confidencial toda aquella que LA PARTE DIVULGANTE identifique como tal, incluyendo pero sin limitarse a: datos financieros, planes de negocio, tecnología, metodologías, bases de datos, listas de clientes y cualquier otro dato técnico o comercial." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "TERCERA. OBLIGACIONES DE LA PARTE RECEPTORA" }] },
        { type: "paragraph", content: [{ type: "text", text: "LA PARTE RECEPTORA se obliga a: a) Mantener la confidencialidad absoluta; b) Usar la información únicamente para el propósito pactado; c) No copiar, reproducir o transmitir la información; d) Notificar inmediatamente cualquier divulgación no autorizada." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "CUARTA. VIGENCIA" }] },
        { type: "paragraph", content: [{ type: "text", text: "Las obligaciones de confidencialidad tendrán vigencia de {{vigencia_meses}} meses a partir de la fecha de este convenio y subsistirán por 3 años adicionales tras su terminación." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "QUINTA. DAÑOS Y PERJUICIOS" }] },
        { type: "paragraph", content: [{ type: "text", text: "El incumplimiento de las obligaciones de confidencialidad dará derecho a LA PARTE DIVULGANTE a reclamar daños y perjuicios, incluyendo lucro cesante y daño emergente." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "SEXTA. JURISDICCIÓN" }] },
        { type: "paragraph", content: [{ type: "text", text: "Para la resolución de controversias, las partes se someten a los Tribunales de {{ciudad}}." }] },
        { type: "paragraph", content: [{ type: "text", text: "Firman en {{ciudad}}.\n\n_________________________\nPARTE DIVULGANTE: {{divulgante_nombre}}\n\n_________________________\nPARTE RECEPTORA: {{receptor_nombre}}" }] },
      ],
    }),
  },
  {
    id: "tmpl_contrato_trabajo",
    name: "Contrato Individual de Trabajo",
    description: "Contrato individual de trabajo conforme a la Ley Federal del Trabajo",
    category: "EMPLOYMENT" as const,
    areaOfLaw: "LABORAL" as const,
    variables: {
      fields: [
        { key: "patron_nombre", label: "Razón social del patrón", type: "text", required: true },
        { key: "patron_rfc", label: "RFC del patrón", type: "text", required: true },
        { key: "trabajador_nombre", label: "Nombre del trabajador", type: "text", required: true },
        { key: "trabajador_curp", label: "CURP del trabajador", type: "text", required: true },
        { key: "puesto", label: "Puesto o categoría", type: "text", required: true },
        { key: "salario_diario", label: "Salario diario (MXN)", type: "number", required: true },
        { key: "jornada", label: "Tipo de jornada (diurna/nocturna/mixta)", type: "text", required: true },
        { key: "lugar_trabajo", label: "Lugar de trabajo", type: "text", required: true },
        { key: "fecha_inicio", label: "Fecha de inicio", type: "date", required: true },
        { key: "ciudad", label: "Ciudad", type: "text", required: true },
      ],
    },
    content: JSON.stringify({
      type: "doc",
      content: [
        { type: "heading", attrs: { level: 1 }, content: [{ type: "text", text: "CONTRATO INDIVIDUAL DE TRABAJO" }] },
        { type: "paragraph", content: [{ type: "text", text: "En {{ciudad}}, a {{fecha_inicio}}, con fundamento en los artículos 20, 24 y 25 de la Ley Federal del Trabajo, se celebra el presente Contrato Individual de Trabajo entre:" }] },
        { type: "paragraph", content: [{ type: "text", text: "EL PATRÓN: {{patron_nombre}}, RFC: {{patron_rfc}}\nEL TRABAJADOR: {{trabajador_nombre}}, CURP: {{trabajador_curp}}" }] },
        { type: "heading", attrs: { level: 2 }, content: [{ type: "text", text: "CLÁUSULAS" }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "PRIMERA. PUESTO Y ACTIVIDADES" }] },
        { type: "paragraph", content: [{ type: "text", text: "EL TRABAJADOR prestará sus servicios como {{puesto}}, realizando las actividades propias de dicho puesto y las que le asigne EL PATRÓN conforme a sus facultades de dirección." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "SEGUNDA. JORNADA DE TRABAJO" }] },
        { type: "paragraph", content: [{ type: "text", text: "La jornada de trabajo será de tipo {{jornada}}, en términos del artículo 60 de la LFT, con un máximo de 8 horas diarias y 48 semanales para jornada diurna." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "TERCERA. SALARIO" }] },
        { type: "paragraph", content: [{ type: "text", text: "EL PATRÓN pagará a EL TRABAJADOR un salario diario de ${{salario_diario}}.00 M.N., que se cubrirá de forma semanal/quincenal [indicar], mediante depósito en cuenta bancaria o en efectivo." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "CUARTA. LUGAR DE TRABAJO" }] },
        { type: "paragraph", content: [{ type: "text", text: "EL TRABAJADOR prestará sus servicios en {{lugar_trabajo}}, pudiendo ser reubicado de común acuerdo." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "QUINTA. PRESTACIONES" }] },
        { type: "paragraph", content: [{ type: "text", text: "EL TRABAJADOR tendrá derecho a todas las prestaciones mínimas de ley: vacaciones (Art. 76 LFT), prima vacacional (25%), aguinaldo (15 días), reparto de utilidades (PTU) y seguridad social (IMSS/INFONAVIT)." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "SEXTA. OBLIGACIONES DEL TRABAJADOR" }] },
        { type: "paragraph", content: [{ type: "text", text: "EL TRABAJADOR se obliga a: a) Prestar el servicio con eficiencia y esmero; b) Observar las medidas de seguridad e higiene; c) Guardar discreción sobre asuntos confidenciales; d) Someterse a los exámenes médicos requeridos." }] },
        { type: "paragraph", content: [{ type: "text", text: "Firman en {{ciudad}} el {{fecha_inicio}}.\n\n_________________________\nEL PATRÓN\n{{patron_nombre}}\n\n_________________________\nEL TRABAJADOR\n{{trabajador_nombre}}" }] },
      ],
    }),
  },
  {
    id: "tmpl_poder_notarial",
    name: "Poder Notarial General",
    description: "Instrumento notarial para otorgamiento de poder general para actos de administración y de dominio",
    category: "POWER_OF_ATTORNEY" as const,
    areaOfLaw: "NOTARIAL" as const,
    variables: {
      fields: [
        { key: "poderdante_nombre", label: "Nombre del poderdante", type: "text", required: true },
        { key: "poderdante_rfc", label: "RFC del poderdante", type: "text", required: true },
        { key: "apoderado_nombre", label: "Nombre del apoderado", type: "text", required: true },
        { key: "apoderado_rfc", label: "RFC del apoderado", type: "text", required: true },
        { key: "tipo_poder", label: "Tipo de poder (administración/dominio/pleitos)", type: "text", required: true },
        { key: "ciudad", label: "Ciudad", type: "text", required: true },
        { key: "notario_numero", label: "Número de notaría", type: "number", required: true },
      ],
    },
    content: JSON.stringify({
      type: "doc",
      content: [
        { type: "heading", attrs: { level: 1 }, content: [{ type: "text", text: "PODER NOTARIAL GENERAL" }] },
        { type: "paragraph", content: [{ type: "text", text: "NOTA: Este documento requiere formalización ante Notario Público para su plena validez jurídica conforme al artículo 2555 del CCF." }] },
        { type: "paragraph", content: [{ type: "text", text: "Ante la Notaría Pública Número {{notario_numero}} de {{ciudad}}, a _____ de __________ de _____:" }] },
        { type: "heading", attrs: { level: 2 }, content: [{ type: "text", text: "OTORGAMIENTO" }] },
        { type: "paragraph", content: [{ type: "text", text: "Yo, {{poderdante_nombre}}, RFC: {{poderdante_rfc}}, por medio del presente instrumento OTORGO PODER GENERAL PARA {{tipo_poder}} a favor de {{apoderado_nombre}}, RFC: {{apoderado_rfc}}." }] },
        { type: "heading", attrs: { level: 2 }, content: [{ type: "text", text: "FACULTADES" }] },
        { type: "paragraph", content: [{ type: "text", text: "Las facultades otorgadas incluyen, de manera enunciativa mas no limitativa: a) Representar al poderdante ante toda clase de autoridades administrativas y judiciales; b) Suscribir documentos y contratos; c) Administrar y disponer de bienes; d) Cobrar y recibir pagos; e) Todas las demás facultades que sean necesarias para el objeto del presente poder." }] },
        { type: "heading", attrs: { level: 2 }, content: [{ type: "text", text: "BASE LEGAL" }] },
        { type: "paragraph", content: [{ type: "text", text: "El presente poder se otorga con fundamento en los artículos 2554, 2555 y 2556 del Código Civil Federal, con todas sus consecuencias jurídicas." }] },
        { type: "paragraph", content: [{ type: "text", text: "El poderdante manifiesta que el presente poder no ha sido revocado ni limitado por instrumento anterior.\n\n_________________________\nEL PODERDANTE\n{{poderdante_nombre}}" }] },
      ],
    }),
  },
  {
    id: "tmpl_acta_constitutiva",
    name: "Acta Constitutiva de S.A. de C.V.",
    description: "Acta constitutiva de Sociedad Anónima de Capital Variable conforme a la LGSM",
    category: "CORPORATE_DEED" as const,
    areaOfLaw: "MERCANTIL" as const,
    variables: {
      fields: [
        { key: "razon_social", label: "Razón social (sin S.A. de C.V.)", type: "text", required: true },
        { key: "objeto_social", label: "Objeto social de la empresa", type: "text", required: true },
        { key: "capital_fijo", label: "Capital social fijo (MXN)", type: "number", required: true },
        { key: "domicilio_social", label: "Domicilio social", type: "text", required: true },
        { key: "duracion_anos", label: "Duración en años", type: "number", required: true },
        { key: "socio1_nombre", label: "Nombre del primer socio", type: "text", required: true },
        { key: "socio2_nombre", label: "Nombre del segundo socio", type: "text", required: false },
        { key: "ciudad", label: "Ciudad", type: "text", required: true },
      ],
    },
    content: JSON.stringify({
      type: "doc",
      content: [
        { type: "heading", attrs: { level: 1 }, content: [{ type: "text", text: "ACTA CONSTITUTIVA DE SOCIEDAD ANÓNIMA DE CAPITAL VARIABLE" }] },
        { type: "paragraph", content: [{ type: "text", text: "NOTA: Requiere protocolización ante Notario Público e inscripción en el Registro Público de Comercio." }] },
        { type: "paragraph", content: [{ type: "text", text: "En {{ciudad}}, siendo las _____ horas del día _____ de __________ de _____, los suscritos, {{socio1_nombre}} y {{socio2_nombre}}, constituyen una Sociedad Anónima de Capital Variable bajo las siguientes:" }] },
        { type: "heading", attrs: { level: 2 }, content: [{ type: "text", text: "BASES CONSTITUTIVAS" }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "PRIMERA. DENOMINACIÓN" }] },
        { type: "paragraph", content: [{ type: "text", text: "La sociedad se denominará \"{{razon_social}}, S.A. de C.V.\", de conformidad con el artículo 2 de la Ley General de Sociedades Mercantiles (LGSM)." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "SEGUNDA. OBJETO SOCIAL" }] },
        { type: "paragraph", content: [{ type: "text", text: "El objeto social de la empresa será: {{objeto_social}}. Así como todas las actividades relacionadas, complementarias o conexas." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "TERCERA. DOMICILIO" }] },
        { type: "paragraph", content: [{ type: "text", text: "El domicilio social será: {{domicilio_social}}. La sociedad podrá establecer sucursales y agencias en cualquier lugar de la República Mexicana o en el extranjero." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "CUARTA. DURACIÓN" }] },
        { type: "paragraph", content: [{ type: "text", text: "La duración de la sociedad será de {{duracion_anos}} años, contados a partir de la inscripción en el Registro Público de Comercio." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "QUINTA. CAPITAL SOCIAL" }] },
        { type: "paragraph", content: [{ type: "text", text: "El capital social fijo es de ${{capital_fijo}}.00 M.N., dividido en acciones nominativas de igual valor. El capital variable es ilimitado. Las acciones serán suscritas y pagadas en los términos del artículo 89 de la LGSM." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "SEXTA. ADMINISTRACIÓN" }] },
        { type: "paragraph", content: [{ type: "text", text: "La administración de la sociedad estará a cargo de un Consejo de Administración o de un Administrador Único, según determine la Asamblea de Accionistas." }] },
        { type: "paragraph", content: [{ type: "text", text: "Los accionistas fundadores firman la presente acta.\n\n_________________________\n{{socio1_nombre}}\n\n_________________________\n{{socio2_nombre}}" }] },
      ],
    }),
  },
  {
    id: "tmpl_amparo_indirecto",
    name: "Demanda de Amparo Indirecto",
    description: "Escrito inicial de demanda de amparo indirecto ante Juzgado de Distrito conforme a la Ley de Amparo",
    category: "AMPARO_PETITION" as const,
    areaOfLaw: "CONSTITUCIONAL" as const,
    variables: {
      fields: [
        { key: "quejoso_nombre", label: "Nombre del quejoso", type: "text", required: true },
        { key: "quejoso_domicilio", label: "Domicilio del quejoso para notificaciones", type: "text", required: true },
        { key: "autoridad_responsable", label: "Autoridad responsable", type: "text", required: true },
        { key: "acto_reclamado", label: "Acto reclamado", type: "text", required: true },
        { key: "garantias_violadas", label: "Garantías constitucionales violadas", type: "text", required: true },
        { key: "juzgado_ciudad", label: "Ciudad del Juzgado de Distrito", type: "text", required: true },
      ],
    },
    content: JSON.stringify({
      type: "doc",
      content: [
        { type: "heading", attrs: { level: 1 }, content: [{ type: "text", text: "DEMANDA DE AMPARO INDIRECTO" }] },
        { type: "paragraph", attrs: { textAlign: "center" }, content: [{ type: "text", text: "H. JUZGADO DE DISTRITO EN TURNO EN {{juzgado_ciudad}}" }] },
        { type: "paragraph", content: [{ type: "text", text: "{{quejoso_nombre}}, señalando como domicilio para oír y recibir notificaciones el ubicado en {{quejoso_domicilio}}, autorizando para tales efectos a los abogados que al final se indican, ante Usted con el debido respeto comparezco y expongo:" }] },
        { type: "paragraph", content: [{ type: "text", text: "Que por medio del presente escrito, y con fundamento en los artículos 103 fracción I y 107 de la Constitución Política de los Estados Unidos Mexicanos, así como en los artículos 107 y 108 de la Ley de Amparo, vengo a interponer DEMANDA DE AMPARO INDIRECTO, expresando para ello los siguientes:" }] },
        { type: "heading", attrs: { level: 2 }, content: [{ type: "text", text: "I. AUTORIDAD RESPONSABLE" }] },
        { type: "paragraph", content: [{ type: "text", text: "{{autoridad_responsable}}" }] },
        { type: "heading", attrs: { level: 2 }, content: [{ type: "text", text: "II. ACTO RECLAMADO" }] },
        { type: "paragraph", content: [{ type: "text", text: "{{acto_reclamado}}" }] },
        { type: "heading", attrs: { level: 2 }, content: [{ type: "text", text: "III. PRECEPTOS CONSTITUCIONALES VIOLADOS" }] },
        { type: "paragraph", content: [{ type: "text", text: "Los artículos {{garantias_violadas}} de la Constitución Política de los Estados Unidos Mexicanos." }] },
        { type: "heading", attrs: { level: 2 }, content: [{ type: "text", text: "IV. ANTECEDENTES" }] },
        { type: "paragraph", content: [{ type: "text", text: "[POR COMPLETAR: Narración cronológica y clara de los hechos que motivaron el acto reclamado]" }] },
        { type: "heading", attrs: { level: 2 }, content: [{ type: "text", text: "V. CONCEPTOS DE VIOLACIÓN" }] },
        { type: "paragraph", content: [{ type: "text", text: "PRIMERO.- [POR COMPLETAR: Argumentación jurídica de los conceptos de violación]" }] },
        { type: "heading", attrs: { level: 2 }, content: [{ type: "text", text: "VI. SUSPENSIÓN DEL ACTO RECLAMADO" }] },
        { type: "paragraph", content: [{ type: "text", text: "Solicito se decrete la suspensión provisional y definitiva del acto reclamado, toda vez que su ejecución causaría daños de difícil reparación al quejoso, en términos del artículo 125 de la Ley de Amparo." }] },
        { type: "heading", attrs: { level: 2 }, content: [{ type: "text", text: "PROTESTO LO NECESARIO" }] },
        { type: "paragraph", content: [{ type: "text", text: "{{juzgado_ciudad}}, a _____ de __________ de _____.\n\n_________________________\nEL QUEJOSO\n{{quejoso_nombre}}" }] },
      ],
    }),
  },
  {
    id: "tmpl_escrito_agravios",
    name: "Escrito de Agravios",
    description: "Escrito de expresión de agravios para recurso de apelación en materia civil",
    category: "MOTION" as const,
    areaOfLaw: "CIVIL" as const,
    variables: {
      fields: [
        { key: "apelante_nombre", label: "Nombre del apelante", type: "text", required: true },
        { key: "apelado_nombre", label: "Nombre del apelado", type: "text", required: true },
        { key: "expediente", label: "Número de expediente", type: "text", required: true },
        { key: "tribunal", label: "Tribunal de alzada", type: "text", required: true },
        { key: "resolucion_apelada", label: "Resolución que se apela", type: "text", required: true },
        { key: "ciudad", label: "Ciudad", type: "text", required: true },
      ],
    },
    content: JSON.stringify({
      type: "doc",
      content: [
        { type: "heading", attrs: { level: 1 }, content: [{ type: "text", text: "ESCRITO DE EXPRESIÓN DE AGRAVIOS" }] },
        { type: "paragraph", attrs: { textAlign: "center" }, content: [{ type: "text", text: "{{tribunal}}" }] },
        { type: "paragraph", content: [{ type: "text", text: "Expediente: {{expediente}}" }] },
        { type: "paragraph", content: [{ type: "text", text: "{{apelante_nombre}}, en el juicio señalado al rubro, por mi propio derecho, ante Usted respetuosamente comparezco y expongo:" }] },
        { type: "paragraph", content: [{ type: "text", text: "Que vengo a expresar AGRAVIOS en contra de {{resolucion_apelada}}, por las razones siguientes:" }] },
        { type: "heading", attrs: { level: 2 }, content: [{ type: "text", text: "AGRAVIOS" }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "PRIMERO" }] },
        { type: "paragraph", content: [{ type: "text", text: "La resolución impugnada viola en perjuicio del apelante lo dispuesto en el artículo [POR COMPLETAR] del Código de Procedimientos Civiles, toda vez que [POR COMPLETAR: argumentación]." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "SEGUNDO" }] },
        { type: "paragraph", content: [{ type: "text", text: "[POR COMPLETAR: Segundo agravio y su fundamentación]" }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "TERCERO" }] },
        { type: "paragraph", content: [{ type: "text", text: "[POR COMPLETAR: Tercer agravio si aplica]" }] },
        { type: "heading", attrs: { level: 2 }, content: [{ type: "text", text: "PETICIÓN" }] },
        { type: "paragraph", content: [{ type: "text", text: "Por lo anterior, respetuosamente solicito a este H. Tribunal tenga por expresados los presentes agravios y, en su oportunidad, revoque/modifique la resolución apelada." }] },
        { type: "paragraph", content: [{ type: "text", text: "{{ciudad}}, a _____ de __________ de _____.\n\n_________________________\n{{apelante_nombre}}" }] },
      ],
    }),
  },
  {
    id: "tmpl_divorcio_incausado",
    name: "Convenio de Divorcio Incausado",
    description: "Convenio regulador de divorcio incausado (unilateral o por acuerdo) conforme al CCF reformado",
    category: "CONTRACT" as const,
    areaOfLaw: "FAMILIAR" as const,
    variables: {
      fields: [
        { key: "conyuge1_nombre", label: "Nombre del primer cónyuge", type: "text", required: true },
        { key: "conyuge2_nombre", label: "Nombre del segundo cónyuge", type: "text", required: true },
        { key: "fecha_matrimonio", label: "Fecha de matrimonio", type: "date", required: true },
        { key: "regimen_matrimonial", label: "Régimen matrimonial (sociedad conyugal/separación de bienes)", type: "text", required: true },
        { key: "hijos", label: "¿Hay hijos menores? (sí/no)", type: "text", required: true },
        { key: "pension_alimenticia", label: "Pensión alimenticia acordada", type: "text", required: true },
        { key: "ciudad", label: "Ciudad", type: "text", required: true },
      ],
    },
    content: JSON.stringify({
      type: "doc",
      content: [
        { type: "heading", attrs: { level: 1 }, content: [{ type: "text", text: "CONVENIO REGULADOR DE DIVORCIO INCAUSADO" }] },
        { type: "paragraph", content: [{ type: "text", text: "En {{ciudad}}, a _____ de __________ de _____, los CC. {{conyuge1_nombre}} y {{conyuge2_nombre}}, quienes contrajeron matrimonio en fecha {{fecha_matrimonio}} bajo el régimen de {{regimen_matrimonial}}, celebran el siguiente Convenio Regulador con motivo de su divorcio incausado, en términos del artículo 266 del Código Civil Federal:" }] },
        { type: "heading", attrs: { level: 2 }, content: [{ type: "text", text: "CLÁUSULAS" }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "PRIMERA. GUARDA Y CUSTODIA" }] },
        { type: "paragraph", content: [{ type: "text", text: "Respecto a los hijos menores ({{hijos}}): [POR COMPLETAR: Acuerdos de guarda y custodia, visitas y convivencias conforme al interés superior del menor]." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "SEGUNDA. PENSIÓN ALIMENTICIA" }] },
        { type: "paragraph", content: [{ type: "text", text: "{{pension_alimenticia}}, de conformidad con los artículos 308 y siguientes del CCF." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "TERCERA. LIQUIDACIÓN DE SOCIEDAD CONYUGAL" }] },
        { type: "paragraph", content: [{ type: "text", text: "[POR COMPLETAR: Distribución de bienes de la sociedad conyugal o declaración de que no existen bienes que partir bajo separación de bienes]." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "CUARTA. USO DEL DOMICILIO CONYUGAL" }] },
        { type: "paragraph", content: [{ type: "text", text: "[POR COMPLETAR: Acuerdo sobre el uso del domicilio conyugal mientras se resuelve el divorcio y ulterior disposición]." }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "QUINTA. COMPENSACIÓN" }] },
        { type: "paragraph", content: [{ type: "text", text: "[POR COMPLETAR: En su caso, compensación en términos del artículo 267 del CCF al cónyuge que se dedicó preponderantemente al hogar]." }] },
        { type: "paragraph", content: [{ type: "text", text: "Las partes manifiestan su conformidad con los términos del presente convenio, el cual presentarán ante el Juez del Registro Civil o Juzgado Familiar competente.\n\n_________________________\n{{conyuge1_nombre}}\n\n_________________________\n{{conyuge2_nombre}}" }] },
      ],
    }),
  },
];

async function main() {
  console.log("Seeding templates...");

  for (const tpl of templates) {
    await prisma.template.upsert({
      where: { id: tpl.id },
      update: {
        name: tpl.name,
        description: tpl.description,
        category: tpl.category,
        areaOfLaw: tpl.areaOfLaw,
        content: tpl.content,
        variables: tpl.variables,
        isSystem: true,
        orgId: null,
      },
      create: {
        id: tpl.id,
        name: tpl.name,
        description: tpl.description,
        category: tpl.category,
        areaOfLaw: tpl.areaOfLaw,
        content: tpl.content,
        variables: tpl.variables,
        isSystem: true,
        orgId: null,
      },
    });
    console.log(`  Upserted: ${tpl.name}`);
  }

  console.log("Seeding complete.");
}

main().catch(console.error).finally(() => prisma.$disconnect());
